
    create table "employee_schedule_list" (
        employee_id bigint not null,
        "schedule_list_id" bigint not null unique
    );

    create table employee (
        is_active boolean not null,
        id bigint generated by default as identity,
        employee_role varchar(255) check (employee_role in ('HairStylist','Manicure')),
        name varchar(255) not null,
        primary key (id)
    );

    create table "tb-schedule" (
        appointment_date timestamp(6) not null,
        employee_id bigint,
        id bigint generated by default as identity,
        client_name varchar(255) not null,
        end_time varchar(255) not null check (end_time in ('H_8_00','H_8_30','H_9_00','H_9_30','H_10_00','H_10_30','H_11_00','H_11_30','H_12_00','H_12_30','H_13_00','H_13_30','H_14_00','H_14_30','H_15_00','H_15_30','H_16_00','H_16_30','H_17_00','H_17_30','H_18_00','H_18_30','H_19_00','H_19_30','H_20_00','H_20_30','H_21_00','H_21_30','H_22_00')),
        service_booked varchar(255) not null,
        start_time varchar(255) not null check (start_time in ('H_8_00','H_8_30','H_9_00','H_9_30','H_10_00','H_10_30','H_11_00','H_11_30','H_12_00','H_12_30','H_13_00','H_13_30','H_14_00','H_14_30','H_15_00','H_15_30','H_16_00','H_16_30','H_17_00','H_17_30','H_18_00','H_18_30','H_19_00','H_19_30','H_20_00','H_20_30','H_21_00','H_21_30','H_22_00')),
        primary key (id)
    );

    alter table if exists "employee_schedule_list" 
       add constraint FK86jni52xw96gtalcskmp8qwa5 
       foreign key ("schedule_list_id") 
       references "tb-schedule";

    alter table if exists "employee_schedule_list" 
       add constraint FKo9w88kxltja1rfhhjmbcusocf 
       foreign key (employee_id) 
       references employee;

    alter table if exists "tb-schedule" 
       add constraint FKfm84lwap6vsaw89p6p76jgain 
       foreign key (employee_id) 
       references employee;
