
    create table tb_employee (
        is_active boolean not null,
        id bigint generated by default as identity,
        name varchar(255) not null,
        role varchar(255) check (role in ('HairStylist','Manicure')),
        primary key (id)
    );

    create table tb_employee_schedule_list (
        employee_id bigint not null,
        schedule_list_id bigint not null unique
    );

    create table tb_schedule (
        appointment_date timestamp(6) not null,
        employee_id bigint,
        id bigint generated by default as identity,
        client_name varchar(255) not null,
        end_time varchar(255) not null check (end_time in ('H_8_00','H_8_30','H_9_00','H_9_30','H_10_00','H_10_30','H_11_00','H_11_30','H_12_00','H_12_30','H_13_00','H_13_30','H_14_00','H_14_30','H_15_00','H_15_30','H_16_00','H_16_30','H_17_00','H_17_30','H_18_00','H_18_30','H_19_00','H_19_30','H_20_00','H_20_30','H_21_00','H_21_30','H_22_00')),
        service_booked varchar(255) not null,
        start_time varchar(255) not null check (start_time in ('H_8_00','H_8_30','H_9_00','H_9_30','H_10_00','H_10_30','H_11_00','H_11_30','H_12_00','H_12_30','H_13_00','H_13_30','H_14_00','H_14_30','H_15_00','H_15_30','H_16_00','H_16_30','H_17_00','H_17_30','H_18_00','H_18_30','H_19_00','H_19_30','H_20_00','H_20_30','H_21_00','H_21_30','H_22_00')),
        primary key (id)
    );

    alter table if exists tb_employee_schedule_list 
       add constraint FKny86s4kq3lymvatcx7v4qbp0r 
       foreign key (schedule_list_id) 
       references tb_schedule;

    alter table if exists tb_employee_schedule_list 
       add constraint FK6ik2bflvkd7hqxchbagoydtw0 
       foreign key (employee_id) 
       references tb_employee;

    alter table if exists tb_schedule 
       add constraint FKfh9ysrg5fcwg29vf3fhc36y2o 
       foreign key (employee_id) 
       references tb_employee;

-- Inserir o primeiro registro de employee
INSERT INTO tb_employee (is_active, name, role) VALUES (true, 'Jhonny Azevedo', 'HairStylist');
-- Inserir o segundo registro de employee
INSERT INTO tb_employee (is_active, name, role) VALUES (true, 'Mylena Moraes', 'Manicure');

-- Inserir 3 registros de schedule para o primeiro employee
INSERT INTO tb_schedule (appointment_date, employee_id, client_name, end_time, start_time, service_booked)
VALUES
    ('2023-09-15', 1, 'Cliente 1', 'H_8_30', 'H_8_00', 'Serviço 1'),
    ('2023-09-15', 1, 'Cliente 2', 'H_9_30', 'H_9_00', 'Serviço 2'),
    ('2023-09-15', 1, 'Cliente 3', 'H_10_30', 'H_10_00', 'Serviço 3');


-- Inserir 3 registros de schedule para o segundo employee
INSERT INTO tb_schedule (appointment_date, employee_id, client_name, end_time, start_time, service_booked)
VALUES
    ('2023-09-15', 2, 'Cliente 4', 'H_11_30', 'H_11_00', 'Serviço 4'),
    ('2023-09-15', 2, 'Cliente 5', 'H_14_00', 'H_13_30', 'Serviço 5'),
    ('2023-09-15', 2, 'Cliente 6', 'H_15_00', 'H_14_30', 'Serviço 6');

